version: '3'
services:

  mail-server:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      main:
        ipv4_address: 10.5.0.12
  
  database:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=cls
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
      - "33060:33060"
    command: --init-file /init.sql
    volumes:
        - ./init.sql:/init.sql
    networks:
      main:
        ipv4_address: 10.5.0.10
  
  spring-app:
    build:
      context: ./backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/cls
    ports:
      - "8080:8080"
    networks:
      main:
        ipv4_address: 10.5.0.5
    depends_on:
      - database
      - mail-server
  
  react-app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      main:
        ipv4_address: 10.5.0.2
    depends_on:
      - spring-app
    

networks:
    main:
        ipam:
            driver: default
            config:
                - subnet: 10.5.0.0/16

volumes:
  mysql:
    driver: local
