version: '3'
services:
  mail-server:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  database:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=cls
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
      - "33060:33060"
    networks:
      - myapp_network
  spring-app:
    build:
      context: ./backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/cls
    ports:
      - "8080:8080"
    networks:
      - myapp_network
  react-app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - myapp_network
networks:
  myapp_network:
    name: myapp_network
volumes:
  mysql:
    driver: local
