#!/bin/bash
# Run all required tools to start the CLS project.

echo "Running the CLS project"

#Running the frontend

cd frontend
start cmd.exe "/K npm install && npm start"

#Running Spring Boot

cd ../backend
mvn clean compile exec:java
